name: Process Multiple URLs

on:
  issues:
    types:
      - opened


jobs:
  read_repos_file:
    runs-on: ubuntu-latest
    outputs:
      urls: ${{ steps.read-repo-names.outputs.repo_names }}

    steps:
      - name: Read Repo Names from File
        id: read-repo-names
        run: |
          repo_names=$(cat ./github/workflows/repo-names.json)
          echo $repo_names
          echo "repo_names=$repo_names" >> "$GITHUB_OUTPUT"
        shell: bash

  process-urls:
    needs: read_repos_file
    strategy:
      matrix: ${{ fromJson(needs.read_repos_file.outputs.urls) }}

    runs-on: ubuntu-latest
      
    if: contains(github.event.issue.labels.*.name, 'feature')

    steps:
      - name: Extract and Store Labels
        id: extract_and_store_labels
        run: |
          label_names="${{ join(github.event.issue.labels.*.name, ', ') }}"
          echo "$label_names ------------"
          echo "label_names=$label_names" >> "$GITHUB_OUTPUT"

      - name: Create Issue in Another Repo
        id: create_issue
        uses: dacbd/create-issue-action@v1
        with:
          token: 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
          repo: ${{ matrix.url }}
          title: ${{ github.event.issue.title }}
          labels: ${{ steps.extract_and_store_labels.outputs.label_names }}

      ## Write for matrix outputs workaround
      - uses: cloudposse/github-action-matrix-outputs-write@main
        id: out
        with:
          matrix-step-name: ${{ github.job }}
          matrix-key: ${{ matrix.url }}
          outputs: |-
             html_url: ${{ fromJson(steps.create_issue.outputs.json).html_url }}
              

  read:
      runs-on: ubuntu-latest
      needs: process-urls
      steps:
        - uses: cloudposse/github-action-matrix-outputs-read@main
          id: read
          with:
            matrix-step-name: process-urls

      outputs:
        result: "${{ steps.read.outputs.result }}"


  update-issue-body:
    runs-on: ubuntu-latest
    needs: [read,read_repos_file] 

    steps:
      - name: Update Issue Body
        # if: steps.check_comment.outputs.has_task_list == 'true'
        run: |
          # Extract the issue number and repository name
          issue_number="${{ github.event.issue.number }}"
          repo_name="${{ github.repository }}"
          echo "-------**** --- ${{ needs.read.outputs.result }}"
          # New issue body with the updated task list
          urls=${{ fromJson(needs.read.outputs.result).html_url.Issue-Creation-Child1 }}
          echo "--------- $urls -------------"

          obj=${{ fromJson(needs.read_repos_file.outputs.urls) }} # Corrected syntax
          for u in $obj; do
            echo "********* $u *******"
            echo "----name-----  $u"
            echo "----url------  ${{ fromJson(needs.read.outputs.result).html_url[$u] }}"
          done



          new_body="${{ github.event.issue.body }} ##Child Issues: \n- [ ] $urls"
          echo "----**----- $new_body -----**--------"
          # Update the issue body using the GitHub API
          curl -L \
            -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Naghme98/github-matrix/issues/$issue_number \
            -d "{\"body\":\"$new_body\"}" 
            


