name: Update Issue in Another Repo

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: check
        run: |
          # Your JSON object as a string
          issue_urls={"html_url":{"Issue-Creation-Child1":"https://github.com/Naghme98/Issue-Creation-Child1/issues/45","Issue-Creation-Child2":"https://github.com/Naghme98/Issue-Creation-Child2/issues/27"}}

          #parse this var and get https://githu... 
          #I need it to be a loop style
          #and it can grow later (have more key values inside the html_url)

          star=$(jq --raw-output .html_url "$issue_urls")
          echo $star