name: Update Issue in Another Repo

on:
  workflow_dispatch:

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: check
        run: |
          # Your JSON object as a string
          issue_urls='{"url": ["Issue-Creation-Child1","Issue-Creation-Child2"]}'


          # Access URLs using GitHub Actions expression
          urls=$(echo $issue_urls | jq -r '.html_url')
          echo $urls